Library/Controllers/BookController.cs
using Library.Models.Book;
using Library.Services.Commands;
using Library.Services.Queries;
using Microsoft.AspNetCore.Mvc;
using System.Threading;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly BookQueries bookQueries;
        private readonly AuthorQueries authorQueries;
        private readonly GenresQueries genresQueries;
        private readonly PublishersQueries publishersQueries;

        private readonly BookCommands bookCommands;

        public BookController(BookQueries bookQueries, BookCommands bookCommands,
            AuthorQueries authorQueries, GenresQueries genresQueries, PublishersQueries publishersQueries)
        {
            this.bookQueries = bookQueries;
            this.authorQueries = authorQueries;
            this.genresQueries = genresQueries;
            this.publishersQueries = publishersQueries;
            this.bookCommands = bookCommands;
        }

        public async Task<IActionResult> AddBook()
        {
            ViewBag.Authors = await authorQueries.GetAllAuthors();

            ViewBag.Genres = await genresQueries.GetAllGenres();

            ViewBag.Publishers = await publishersQueries.GetAllPublishers();

            return View(new AddBookViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> AddBook(AddBookViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await bookCommands.AddBook(model, cancellationToken);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public async Task<IActionResult> EditBook(int id)
        {
            ViewBag.Authors = await authorQueries.GetAllAuthors();

            ViewBag.Genres = await genresQueries.GetAllGenres();

            ViewBag.Publishers = await publishersQueries.GetAllPublishers();

            var model = await bookQueries.GetEditBookById(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditBook(EditBookViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await bookCommands.EditBook(model, cancellationToken);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public async Task<IActionResult> DeleteBook(int id, CancellationToken cancellationToken)
        {
            await bookCommands.DeleteBook(id, cancellationToken);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> GetBook(int id, CancellationToken cancellationToken)
        {
            await bookCommands.ChangeBookStatus(id, cancellationToken);

            return RedirectToAction("AllReservations", "Order");
        }
    }
}

Library/Controllers/HomeController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Library.Domain;
using Library.Domain.Entities;
using Library.Models;
using Library.Models.Book;
using Library.Services.Queries;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRepository<BookReview> repositoryBookReview;

        private readonly BookQueries bookQueries;

        public HomeController(IRepository<BookReview> repositoryBookReview, BookQueries bookQueries)
        {
            this.repositoryBookReview = repositoryBookReview;
            this.bookQueries = bookQueries;
        }

        public async Task<IActionResult> Index(string sortsValue, string findsValue, string findText)    
        {

            var books = await bookQueries.GetAllBooks(sortsValue, findsValue, findText);

            ViewBag.FindText = findText;

            return View(books);
        }

        public async Task<IActionResult> BookInfo(int id)  
        {
            var book = await bookQueries.GetBookById(id);

            var reviews = await repositoryBookReview.GetAll()
                .FirstOrDefaultAsync(x => x.BookId == id);

            if (reviews != null)
            {
                ViewBag.Reviews = await bookQueries.GetBookAllComments(reviews.CommentsString);
            }

            return View(book);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library/Controllers/LibrarianController.cs
using AutoMapper;
using Library.Models.Author;
using Library.Models.Genre;
using Library.Models.Publisher;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Library.Models.Book;
using Library.Services.Queries;
using Library.Services.Commands;
using Microsoft.AspNetCore.Authorization;
using Library.Domain.Entities;

namespace Library.Controllers
{
    [Authorize(Roles = RolesNames.LibrarianName)]
    public class LibrarianController : Controller
    {

        public LibrarianController()
        {

        }

        public IActionResult ControlPanel()
        {
            return View();
        }
    }
}

Library/Views/Home/BookInfo.cshtml
@model ListBookInfoViewModel

<h3>Подробнее</h3>

<div>
    <img src="@Model.ImageUrl" alt="@Model.Name" />
    <h4>@Model.Name</h4>
    <p>@Model.Author</p>
    <p>@Model.Genre</p>
    <p>@Model.Publisher</p>
    <p>@Model.Status</p>
    <form asp-action="LeaveFeedback" asp-controller="Order">
        <input type="radio" name="grade" value="1" id="grade1" />
        <label for="grade1">1</label>

        <input type="radio" name="grade" value="2" id="grade2" />
        <label for="grade2">2</label>

        <input type="radio" name="grade" value="3" id="grade3" />
        <label for="grade3">3</label>

        <input type="radio" name="grade" value="4" id="grade4" />
        <label for="grade4">4</label>

        <input type="radio" name="grade" value="5" id="grade5" />
        <label for="grade5">5</label>

        <textarea name="commentText"></textarea>
        <input type="hidden" value="@Model.Id" name="bookId" />
        <input type="submit" value="Отправить" />
    </form>
    <div>
        @if (ViewBag.Reviews != null)
        {
            @foreach (var item in ViewBag.Reviews)
            {
                <h3>@item.Name</h3>
                <p>@item.Grade</p>
                <p>@item.CommentText</p>
            }
        }
        else
        {
            <h3>На данный момент нет отзывов!</h3>
        }

    </div>

</div>

Library/Views/Home/Index.cshtml
@model IEnumerable<ListBookViewModel>

<h3>Книги</h3>
<head>
    <style>
        .disabled {
            pointer-events: none;
        }

        .sort {
            display: flex;
            margin: 10px;
        }
    </style>
</head>
<form asp-action="Index" asp-controller="Home" method="get">
    <div class="sort">
        <div class="sort">
            <h5>Сортировать по:</h5>
            <select name="sortsValue">
                <option selected="selected" value="0" disabled="disabled">Выберите тип</option>
                <option value="author">Автор</option>
                <option value="genre">Жанр</option>
                <option value="publisher">Издаетль</option>
                <option value="name">Название книги</option>
            </select>
        </div>
        <div class="sort">
            <select name="findsValue" data="@ViewBag.SortsValue">
                <option selected="selected" value="0" disabled="disabled">Выберите тип</option>
                <option value="author">Автор</option>
                <option value="genre">Жанр</option>
                <option value="publisher">Издаетль</option>
                <option value="name">Название книги</option>
            </select>
            <input type="text" name="findText" value="@ViewBag.FindText" />
            <input type="submit" value="Поиск" />
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(k => k.Name)</th>
            <th>@Html.DisplayNameFor(k => k.Author)</th>
            <th>@Html.DisplayNameFor(k => k.Genre)</th>
            <th>@Html.DisplayNameFor(k => k.Publisher)</th>
            <th>@Html.DisplayNameFor(k => k.Status)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Name</td>
                <td>@book.Author</td>
                <td>@book.Genre</td>
                <td>@book.Publisher</td>
                <td>@Library.Services.GetEmunName.GetName(book.Status)</td>
                <td>
                    <a class="btn btn-info" asp-action="BookInfo" asp-route-id="@book.Id">Подробнее</a>
                    @if (@book.Status == Library.Domain.Entities.Status.Avaliable)
                    {
                        <a class="btn btn-danger" asp-action="ToBook" asp-controller="Order"
                   asp-route-id="@book.Id">Забронировать</a>
                    }
                    else
                    {
                        <a class="btn btn-danger disabled" asp-action="ToBook" asp-controller="Order"
                   asp-route-id="@book.Id">Забронировать</a>
                    }
                    <a class="btn btn-danger" asp-action="EditBook" asp-controller="Book" asp-controller="Librarian"
                   asp-route-id="@book.Id">Изменить</a>
                    <a class="btn btn-danger" asp-action="DeleteBook" asp-controller="Book" asp-controller="Librarian"
                   asp-route-id="@book.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>