Library/Controllers/LibrarianController.cs
using AutoMapper;
using Library.Models.Author;
using Library.Models.Genre;
using Library.Models.Publisher;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Library.Models.Book;
using Library.Services.Queries;
using Library.Services.Commands;
using Microsoft.AspNetCore.Authorization;
using Library.Domain.Entities;

namespace Library.Controllers
{
    [Authorize(Roles = RolesNames.LibrarianName)]
    public class LibrarianController : Controller
    {

        public LibrarianController()
        {

        }

        public IActionResult ControlPanel()
        {
            return View();
        }
    }
}

Library/Controllers/RolesController.cs
using Library.Domain.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Library.Services.Queries;
using Library.Services.Commands;
using Microsoft.AspNetCore.Authorization;

namespace Library.Controllers
{
    [Authorize(Roles = RolesNames.AdminName)]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;
        private readonly UserQueries userQueries;
        private readonly RoleQueries roleQueries;
        private readonly RoleCommands roleCommands;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager,
            UserQueries userQueries, RoleQueries roleQueries, RoleCommands roleCommands)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.userQueries = userQueries;
            this.roleQueries = roleQueries;
            this.roleCommands = roleCommands;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await roleQueries.GetAllRoles();

            return View(roles);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                await roleManager.CreateAsync(new IdentityRole(name));

                return RedirectToAction("Index");
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role != null)
            {
                await roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UserList()
        {
            var users = await userQueries.GetAllUsersEmails();

            return View(users);
        }

        public async Task<IActionResult> Edit(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);

            if (user != null)
            {
                var userRoles = await roleQueries.GetUserRoles(user);

                return View(userRoles);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {

            var user = await userManager.FindByIdAsync(userId);

            if (user != null)
            {
                await roleCommands.EditUserRole(user, roles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Library/Controllers/UsersController.cs
using AutoMapper;
using Library.Domain.Entities;
using Library.Models.User;
using Library.Services.Commands;
using Library.Services.Queries;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Library.Controllers
{
    [Authorize(Roles = RolesNames.AdminName)]
    public class UsersController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IMapper mapper;

        private readonly UserCommands userCommands;
        private readonly UserQueries userQueries;
        public UsersController(UserManager<User> userManager, IMapper mapper, UserCommands userCommands, UserQueries userQueries)
        {
            this.userManager = userManager;
            this.mapper = mapper;
            this.userCommands = userCommands;
            this.userQueries = userQueries;
        }

        public async Task<IActionResult> Index()
        {
            var users = await userQueries.GetAllUsersFullInfo();

            return View(users);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                await userCommands.CreateNewUser(model);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }
            
            var model = new EditUserViewModel { Id = user.Id, Email = user.Email, UserName = user.Email, PhoneNumber = user.PhoneNumber };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(model.Id);

                if (user != null)
                {
                    await userCommands.EditUser(user, model);

                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user != null)
            {
                await userManager.DeleteAsync(user);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ConfirmUserEmail(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user != null)
            {
                user.EmailConfirmed = true;
                await userManager.UpdateAsync(user);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await userManager.FindByIdAsync(model.Id);

                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    var result =
                        await _passwordValidator.ValidateAsync(userManager, user, model.NewPassword);

                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await userManager.UpdateAsync(user);
                    }

                    return RedirectToAction("Index");

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="MyReservations">Моя бронирования</a>
                            </li>

                            @if (User.IsInRole(Library.Domain.Entities.RolesNames.AdminName))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Управление пользователями</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Управление ролями</a>
                                </li>
                            }

                            @if (User.IsInRole(Library.Domain.Entities.RolesNames.LibrarianName))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Librarian" asp-action="ControlPanel">Панель управления</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="AllReservations">Все бронирования</a>
                                </li>
                            }

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["alert"] != null)
            {
                <div class="alert">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                    <strong>Ошибка!</strong> @TempData["alert"]
                </div>
            }
            @if (TempData["succses-alert"] != null)
            {
                <div class="succses-alert">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                    <strong>Информация!</strong> @TempData["succses-alert"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>